version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  semantic-release: trustedshops-public/semantic-release@5.0.0
  codecov: codecov/codecov@3.2.5

executors:
  java8:
    docker:
      - image: cimg/openjdk:8.0.345
    environment:
      MAVEN_OPTS: -Xmx3512m -Djansi.force=true
      SPRING_OUTPUT_ANSI_ENABLED: always
  java11:
    docker:
      - image: cimg/openjdk:11.0.16
    environment:
      MAVEN_OPTS: -Xmx3512m -Djansi.force=true
      SPRING_OUTPUT_ANSI_ENABLED: always

jobs:
  coverage:
    executor: java11
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Run tests to record coverage
                command: mvn test
            - codecov/upload
  build:
    executor: java8
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Build
                command: mvn -DskipTests=true package
            - run:
                name: Generate javadoc
                command: mvn -DskipTests=true site
            - persist_to_workspace:
                root: target/
                paths:
                  - '*.jar'
  deploy:
    executor: java8
    parameters:
      version_suffix:
        type: string
        default: ""
        description: Suffix to append to version
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Set version to latest tag
                command: |
                  export VERSION=$(git describe --dirty --tags 2>/dev/null || git log -1 --pretty=format:%h)
                  mvn versions:set -DnewVersion="${VERSION}<<parameters.version_suffix>>"
            - run:
                name: Import gpg key
                command: |
                  echo -e "$GPG_PRIVATE_KEY"  | gpg --import --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback
            - run:
                name: Run maven deploy
                command: mvn -s .circleci/maven-settings.xml  -Possrh -DskipTests=true clean site javadoc:jar gpg:sign package deploy

workflows:
  continuous:
    jobs:
      - maven/test:
          matrix:
            alias: test
            parameters:
              executor: [ java8, java11 ]
      - coverage:
          requires:
            - test
      - build:
          requires:
            - test
      - deploy:
          name: deploy-snapshot
          version_suffix: "-SNAPSHOT"
          context:
            - gpg
            - maven-central
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
      - semantic-release/with_changelog_github_config:
          name: semantic-release
          context:
            - semantic-release
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy:
          context:
            - gpg
            - maven-central
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only: /.*/
