version: 2.1

orbs:
  maven: circleci/maven@1.3.0

executors:
  java8:
    docker:
      - image: cimg/openjdk:8.0.302
    environment:
      MAVEN_OPTS: -Xmx3512m -Djansi.force=true
      SPRING_OUTPUT_ANSI_ENABLED: always
  java11:
    docker:
      - image: cimg/openjdk:11.0.12
    environment:
      MAVEN_OPTS: -Xmx3512m -Djansi.force=true
      SPRING_OUTPUT_ANSI_ENABLED: always

jobs:
  build:
    executor: java8
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Build
                command: mvn -DskipTests=true package
            - run:
                name: Generate javadoc
                command: mvn -DskipTests=true site
            - run:
                name: Create package
                command: mvn -DskipTests=true package
            - persist_to_workspace:
                root: target/
                paths:
                  - '*.jar'
  deploy:
    executor: java8
    parameters:
      version_suffix:
        type: string
        default: "-SNAPSHOT"
        description: Suffix to append to version
    steps:
      - checkout
      - maven/witch-cache:
          steps:
            - run:
                name: Set version to latest tag
                command: |
                  export VERSION=$(git describe --dirty --tags 2>/dev/null || git log -1 --pretty=format:%h)
                  mvn versions:set -DnewVersion="${VERSION}<<parameters.version_suffix>>"
            - run:
                name: Import gpg key
                command: |
                  echo -e "$GPG_PRIVATE_KEY"  | gpg --import --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback
            - run:
                name: Run maven deploy
                command: mvn -s .circleci/maven-settings.xml -Dskiptests=true clean deploy

workflows:
  continuous:
    jobs:
      - maven/test:
          matrix:
            alias: test
            parameters:
              executor: [ java8, java11 ]
      - build:
          requires:
            - test
      - deploy:
          version_suffix: "-SNAPSHOT"
          context:
            - gpg
            - maven-central
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
